package no.uio.ifi.titanic.ui.homeScreen.homeScreenComponents.weather

import androidx.compose.runtime.Composable

@Composable
fun getNorwegianWeatherDescription(englishDescription: String): String{
    val descriptionsMap = mapOf(
        "clearsky_day" to "Klar himmel",
        "clearsky_night" to "Klar himmel",
        "clearsky_polartwilight" to "Klar himmel",
        "fair_day" to "Lettskyet",
        "fair_night" to "Lettskyet",
        "fair_polartwilight" to "Lettskyet",
        "partlycloudy_day" to "Delvis skyet",
        "partlycloudy_night" to "Delvis skyet",
        "partlycloudy_polartwilight" to "Delvis skyet",
        "cloudy" to "Overskyet",
        "rainshowers_day" to "Regnbyger",
        "rainshowers_night" to "Regnbyger",
        "rainshowers_polartwilight" to "Regnbyger",
        "rainshowersandthunder_day" to "Regnbyger og torden",
        "rainshowersandthunder_night" to "Regnbyger og torden",
        "rainshowersandthunder_polartwilight" to "Regnbyger og torden",
        "sleetshowers_day" to "Sluddbyger",
        "sleetshowers_night" to "Sluddbyger",
        "sleetshowers_polartwilight" to "Sluddbyger",
        "snowshowers_day" to "Snøbyger",
        "snowshowers_night" to "Snøbyger",
        "snowshowers_polartwilight" to "Snøbyger",
        "rain" to "Regn",
        "heavyrain" to "Kraftig regn",
        "heavyrainandthunder" to "Kraftig regn og torden",
        "sleet" to "Sludd",
        "snow" to "Snø",
        "snowandthunder" to "Snø og torden",
        "fog" to "Tåke",
        "sleetshowersandthunder_day" to "Sluddbyger og torden",
        "sleetshowersandthunder_night" to "Sluddbyger og torden",
        "sleetshowersandthunder_polartwilight" to "Sluddbyger og torden",
        "snowshowersandthunder_day" to "Snøbyger og torden",
        "snowshowersandthunder_night" to "Snøbyger og torden",
        "snowshowersandthunder_polartwilight" to "Snøbyger og torden",
        "rainandthunder" to "Regn og torden",
        "sleetandthunder" to "Sludd og torden",
        "lightrainshowersandthunder_day" to "Lette regnbyger og torden",
        "lightrainshowersandthunder_night" to "Lette regnbyger og torden",
        "lightrainshowersandthunder_polartwilight" to "Lette regnbyger og torden",
        "heavyrainshowersandthunder_day" to "Kraftige regnbyger og torden",
        "heavyrainshowersandthunder_night" to "Kraftige regnbyger og torden",
        "heavyrainshowersandthunder_polartwilight" to "Kraftige regnbyger og torden",
        "lightssleetshowersandthunder_day" to "Lette sluddbyger og torden",
        "lightssleetshowersandthunder_night" to "Lette sluddbyger og torden",
        "lightssleetshowersandthunder_polartwilight" to "Lette sluddbyger og torden",
        "heavysleetshowersandthunder_day" to "Kraftige sluddbyger og torden",
        "heavysleetshowersandthunder_night" to "Kraftige sluddbyger og torden",
        "heavysleetshowersandthunder_polartwilight" to "Kraftige sluddbyger og torden",
        "lightssnowshowersandthunder_day" to "Lette snøbyger og torden",
        "lightssnowshowersandthunder_night" to "Lette snøbyger og torden",
        "lightssnowshowersandthunder_polartwilight" to "Lette snøbyger og torden",
        "heavysnowshowersandthunder_day" to "Kraftige snøbyger og torden",
        "heavysnowshowersandthunder_night" to "Kraftige snøbyger og torden",
        "heavysnowshowersandthunder_polartwilight" to "Kraftige snøbyger og torden",
        "lightrainandthunder" to "Lett regn og torden",
        "lightsleetandthunder" to "Lett sludd og torden",
        "heavysleetandthunder" to "Kraftig sludd og torden",
        "lightsnowandthunder" to "Lett snø og torden",
        "heavysnowandthunder" to "Kraftig snø og torden",
        "lightrainshowers_day" to "Lette regnbyger",
        "lightrainshowers_night" to "Lette regnbyger",
        "lightrainshowers_polartwilight" to "Lette regnbyger",
        "heavyrainshowers_day" to "Kraftige regnbyger",
        "heavyrainshowers_night" to "Kraftige regnbyger",
        "heavyrainshowers_polartwilight" to "Kraftige regnbyger",
        "lightsleetshowers_day" to "Lette sluddbyger",
        "lightsleetshowers_night" to "Lette sluddbyger",
        "lightsleetshowers_polartwilight" to "Lette sluddbyger",
        "heavysleetshowers_day" to "Kraftige sluddbyger",
        "heavysleetshowers_night" to "Kraftige sluddbyger",
        "heavysleetshowers_polartwilight" to "Kraftige sluddbyger",
        "lightsnowshowers_day" to "Lette snøbyger",
        "lightsnowshowers_night" to "Lette snøbyger",
        "lightsnowshowers_polartwilight" to "Lette snøbyger",
        "heavysnowshowers_day" to "Kraftige snøbyger",
        "heavysnowshowers_night" to "Kraftige snøbyger",
        "heavysnowshowers_polartwilight" to "Kraftige snøbyger",
        "lightrain" to "Lett regn",
        "lightsleet" to "Lett sludd",
        "heavysleet" to "Kraftig sludd",
        "lightsnow" to "Lett snø",
        "heavysnow" to "Kraftig snø"
    )

    return descriptionsMap[englishDescription]?.lowercase() ?: ""
}
